version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./main.py:/code/main.py
    restart: always

  db:
    image: postgres:latest
    container_name: bot-database
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
